apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-performance-addon-operator-subscription
  namespace: openshift-performance-addon-operator
spec:
  installPlanApproval: Automatic
  channel: "4.8" 
  name: performance-addon-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace

