apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-performance-addon-operator-subscription
  namespace: redhat-operators
spec:
  channel: "4.7" 
  name: performance-addon-operator
  source: redhat-operators 
  sourceNamespace: openshift-marketplace
