apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: sriov-networknodepolicy-netdevice-mlx-ens5f1
  namespace: openshift-sriov-network-operator
spec:
  deviceType: netdevice
  isRdma: false
  linkType: eth
  mtu: 1500
  nicSelector:
    pfNames: ["ens5f1#0-15"] 
    rootDevices:
    - "0000:3b:00.1"
    vendor: "15b3"
    deviceID: "1015"
  nodeSelector:
    node-role.kubernetes.io/ht: ""
  numVfs: 16
  priority: 10
  resourceName: sriov_netdevice_ens5f1_mlxnic
