# TODO handle namespace with var
resources:
  - performance/01-pao-namespace.yaml
  - performance/021-pao-catalogsource.yaml
#  - performance/02-pao-operatorgroup.yaml
  - performance/03-pao-subscription.yaml
  - sriov/01-sriov-namespace.yaml
  - sriov/02-sriov-operatorgroup.yaml
  - sriov/03-sriov-subscription.yaml
  - nmstate/01-nmstate-namespace.yaml
  - nmstate/02-nmstate-operatorgroup.yaml
  - nmstate/03-nmstate-subscription.yaml
  - nmstate/04-nmstate-instance.yaml
